<?php

//header("Location: index.html");

//Get login credentials
require_once 'databaseCredentials.php';

// Create connection
$conn = new mysqli($servername, $username, $password, $db);

// Check connection
if ($conn->connect_error) {
    die('Connection failed: ' . $conn->connect_error);
}
echo 'Connected successfully' . '<br>';

//Set character set to allow ÅÄÖ
printf("Initial character set: %s\n", mysqli_character_set_name($conn) . '<br>');
if (!mysqli_set_charset($conn, "utf8")) {
    printf("Error loading character set utf8: %s\n", mysqli_error($conn) . '<br>');
    exit();
} else {
    printf("Current character set: %s\n", mysqli_character_set_name($conn) . '<br>');
}
?>
<script type="text/javascript">
    var courseChoice = function(choice){
    console.log("Sending courseChoice");
    var xhr = new XMLHttpRequest();
    var url = "http://script.studieradet.se/kurskurt/courseChoice.php";
    var url = url + "?courseChoice=" + choice;
    xhr.onreadystatechange = function () {
        //Run on success
        if (xhr.readyState === 4 && xhr.status === 200) {
            console.warn(xhr.responseText);
            //Set icsArray of form to the eventList generated by parseICS.php
            var myarray = JSON.parse(xhr.responseText);
            console.log(myarray);
            for (j=document.getElementById('lecture').options.length-1;j>=0;j--){
              document.getElementById('lecture').remove(j);
            }
            for (i=0;i<myarray.data.length;i++){
              var optn = document.createElement("OPTION");
              optn.text = myarray.data[i][1] +  ' ' + myarray.data[i][0];
              optn.value = myarray.data[i][1];  // You can change this to subcategory 
              document.getElementById('lecture').options.add(optn);
            }
        }
    };
    xhr.open("GET", url, true);
    xhr.send(null);
    }
</script>

<?php
//Select and set dropdown menu to values of table

echo "<html>";
echo "<body>";

//Courses
$sql = "SELECT CourseID, CourseName FROM Courses ";
$result = $conn->query($sql);
echo "<select name='course' id='course' onchange='courseChoice(this.value);'>";

if ($result->num_rows > 0) {
  while ($row = $result->fetch_assoc()){
    unset($id, $name);
    $id = $row['CourseID'];
    $name = $row['CourseName'];
    echo '<option value="'.$id.'">'.$id. ' ' .$name.'</option>';
  }
}
else {
  echo 'Error: Select FROM Courses' . $conn->error;
}
echo "</select>";

//Lectures
$sql = "SELECT LectureID, LectureName FROM Lectures ";
$result = $conn->query($sql);
echo "<select name='lecture' id='lecture'>";

if ($result->num_rows > 0) {
  while ($row = $result->fetch_assoc()){
    unset($id, $name);
    $id = $row['LectureID'];
    $name = $row['LectureName'];
    echo '<option value="'.$id.'">'.$id. ' ' .$name.'</option>';
  }
}
else {
  echo 'Error: Select FROM Lectures' . $conn->error;
}

echo "</select>";
echo "</body>";
echo "</html>";


//Close connection
mysqli_close($conn);

?>
